#edited 20191203 JM
#
# VARIABLES  
variable T         index  0.40 0.60 0.80  #0.20 0.25 0.30 0.40 0.50 0.55 0.60 0.70 0.80  
variable num       equal  1 # 2 3 4 5 # for the different initial configurations that you will run
variable N         equal  500  # 500 molecules (500 rigidrods)
variable box       equal  100 # cubic box of volume 10**3
variable t_step    equal  0.005  # this is the timestep. When increased you save time for reaching the equilibrium, 
                                 # but the simulation may crash when too big.
variable mix_steps equal  200000 # how many steps for mixing the initial configuration
variable mix_tau   equal  ${t_step}*${mix_steps} # this is the time in LJ units
variable run_steps equal  2000000 # steps to run simulation in order to reach steady state
variable run_tau   equal  ${t_step}*${run_steps} # this is the time in LJ units

# PARAMETERS    
units lj
atom_style molecular
neighbor 0.4 bin
neigh_modify every 1 delay 1 check yes
comm_modify vel yes

# READ  
read_data input_data_nunchucks_${N}_${box}.file
#read_restart input_data_nunchucks_${N}_${box}_mixed_${mix_tau}_tau.restart 

#  BONDS 
bond_style harmonic
special_bonds lj 0 1 1   
bond_coeff * 500.0 0.98  # the wildcard (*) means to have the same for all bond types.         
bond_coeff 5 50.0 0.98  #changes for nunchucks
      

# ANGLES  
angle_style harmonic
angle_coeff * 500.0  180
#angle_coeff 4 0.1  180 #cahnges for nunchucks
#angle_coeff 5 0.1  180 #changes for nunchucks


# PAIR lj/cut --with interactions, to steady state
pair_style lj/cut 1.0 
pair_modify shift yes
pair_coeff * * 1  1.0  1.12    # excluded volume

# THERMAL   
timestep ${t_step}
thermo   100 # after how may timesteps to give you the output of the values specified in the line below
thermo_style custom step time temp press pe ke etotal vol 
thermo_modify norm no
reset_timestep 0

# FIX
#fix 2 all nph iso 0.5 0.5 100 # in nph condition the box size decreases gradually and hence the density of nunchucks increases
#fix 4 all nve # solver for the system. It is not and NVE but an NVT ensemble since we are using the langevin thermostat
fix 1 all npt temp 300.0 300.0 100.0 iso 0.0 0.0 1000.0
#fix 3 all langevin ${T} ${T} 1 123456 
fix recen1 all recenter INIT INIT INIT

#-- 1st need to mix the system -- no need to do it now

## RUN to steady state
#run ${mix_steps}
#write_restart  input_data_nunchucks_${N}_${box}_mixed_${mix_tau}_tau.restart
#shell touch mix:T_${T}.done


#-- 2nd run the simulation for various T



# DUMP output and pairlocal files
dump 1 all custom 1000 output.dump id mol type x y z vx vy vz 
dump_modify 1 sort id
#file that can be visualised in ovito. It keeps the trajectories
#compute 1 all property/local patom1 patom2
#compute 2 all pair/local dist eng force
#dump 2 all local 10 pairlocal.dump c_1[1] c_1[2] c_2[1] c_2[2] c_2[3] # it keeps the bonds that have been formed. 
# nothing will have beed formed since no attractive potential is specified.



# RUN to steady state
run ${run_steps}


# write restart
#write_restart output.restart

# SHELL commands
#shell cp log.lammps            log_T_${T}_N_${N}_box_${box}_run_${run_tau}_tau_num_${num}.lammps
#shell cp output.restart     output_T_${T}_N_${N}_box_${box}_run_${run_tau}_tau_num_${num}.restart
#shell cp pairlocal.dump  pairlocal_T_${T}_N_${N}_box_${box}_run_${run_tau}_tau_num_${num}.dump
shell cp output.dump        output_T_${T}_N_${N}_box_${box}_run_${run_tau}_tau_num_${num}.dump

shell touch T_${T}.done

clear 

next T
jump in.run
